[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
 
[project]
name = "pysimplicial"
version = "0.1.0"
description = "pysimplicial is an experimental Python library for working with simplicial complexes in the context of topological neural networks"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "siritoriyowai" }]
dependencies = [
    "torch",
    "numpy",
    "networkx",
    "matplotlib",
    "opt_einsum",
]
 
[project.urls]
Repository = "https://github.com/kaifczxc-lab/pysimplicial"